### PR TITLE
Add psalm

### PR DESCRIPTION
**Pull request by VincentLanglet**
pedantic

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@jordisala1991 The psalm error is kinda weird, does it means we don't really support php 8.1 ?

**Comment by jordisala1991** [comment]
I think we do but with sone warnings. But those are related to SonataAdminBundle 3.x right?

**Comment by VincentLanglet** [comment]
Yes we have warning with 8.1 on sonata admin 3 and it's giving a fatal error on psalm here, but not on sonata admin...

**Comment by jordisala1991** [comment]
Sonata Admin 3 is not being tested against php 8.1

**Comment by VincentLanglet** [comment]
> Sonata Admin 3 is not being tested against php 8.1

Oh does that mean that SonataAdmin 3 doesn't support 8.1 and we shouldn't say we support 8.1 on SonataFormatter ?

**Comment by jordisala1991** [comment]
Probably yes, we should remove it from devkit

**Review by jordisala1991 — APPROVED** [review]

**Pull request merged**
