### PR TITLE
SF 3.0 support with BC SF <= 2.8

### PR DESCRIPTION
**Pull request by idchlife**
@core23 @greg0ire 

Guys, could you check this and merge?

### CODE REVIEW

**Comment by greg0ire** [comment]
The tests should pass on every commit of your PR. If you do commitA, and then you add commitB to "fix something", please fixup commitB into commitA.

**Comment by greg0ire** [comment]
ping us when the tests are passing.

**Comment by idchlife** [comment]
@greg0ire I do not really understand what you mean by fixup commitB into commitA.

You mean, if commitA is corrupted/with error, and I add commitB to fix it - all pull request still won't build successfully?

**Comment by greg0ire** [comment]
I mean that there should not be 2 commits : 

- commit A
- commit B, which is commit A's fix
- commit C, which is yet another fix

but just one commit.

To achieve this result, you can either use `git rebase --interactive origin/master`, and fixup both commits into the first one, or use `git reset origin/master` to forget about your commit, then do the commit again (your changes will stay in the working tree, you will just have to commit them again). Then use `git push --force` to replace the branch you pushed with the new branch with only one commit.

**Pull request closed without merging**
