### PR TITLE
Merge of 3.x in master branch

### PR DESCRIPTION
**Pull request by Th3Mouk**
Add the last commits of 3.x on the master

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I'll merge branch by hands.

**Comment by Soullivaneuh** [comment]
@Th3Mouk done.

**Comment by Th3Mouk** [comment]
What the difference with this PR ?

**Comment by Soullivaneuh** [comment]
Merging by PR would create another merge commit. If this can be easily merge without conflict, it's better to do this directly on command line IMO.

**Comment by Th3Mouk** [comment]
thanks

**Comment by greg0ire** [comment]
@soullivaneuh what if you squash?

**Comment by Soullivaneuh** [comment]
On this MR? I'm sure it will squash all the commits onto one. And this is dangerous.

**Comment by greg0ire** [comment]
Ok I wasn't sure

**Pull request closed without merging**
