### PR TITLE
[DEL] Drop support for egeloen/ckeditor-bundle < 2.5

### PR DESCRIPTION
**Pull request by Th3Mouk**
https://github.com/sonata-project/SonataFormatterBundle/pull/146

### CODE REVIEW

**Comment by Th3Mouk** [comment]
@OskarStark could you merge this please ?

**Comment by greg0ire** [comment]
The commit message should look like this : 

```
drop support for egeloen/ckeditor-bundle < 2.5

The ivory_ck_editor.templating.helper service has been renamed, and the old name is not supported.
```

Can you please amend your commit?

**Comment by Th3Mouk** [comment]
@greg0ire ok but it's not too long ?

**Comment by greg0ire** [comment]
Keep the first line short. Add a blank line, then put the rest of the commit message in a paragraph.

**Comment by Th3Mouk** [comment]
@greg0ire :+1: really cool

**Comment by greg0ire** [comment]
More resources : 

- http://rakeroutes.com/blog/deliberate-git/
- http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
- http://stopwritingramblingcommitmessages.com/
- http://www.whatthecommit.com/ :laughing:

**Comment by greg0ire** [comment]
If you use vim, the commit message will be colored in red if you break the rules :)

**Comment by Th3Mouk** [comment]
ok ! yes for rebase -i it's VIM editor

**Comment by greg0ire** [comment]
Ok so it should be vim too when using `git commit` :)

**Comment by greg0ire** [comment]
Good to merge IMO

**Comment by greg0ire** [comment]
… not? tests are failing on a particular job.

**Comment by Th3Mouk** [comment]
@greg0ire that's normal because this versions doesn't support sf3.x

**Comment by Th3Mouk** [comment]
before symfony3 tests was optional

**Comment by greg0ire** [comment]
If it really is optional, it should be in `allow_failures` in .travis.yml, otherwise, it is harder to know if you break the build, because you have to look at the logs every time.

**Comment by Th3Mouk** [comment]
@greg0ire I'm agree but when the https://github.com/sonata-project/SonataFormatterBundle/pull/148 will be merged tests backs green.

**Comment by greg0ire** [comment]
Oh ok, let's wait for it and rebase.

**Comment by core23** [comment]
Can you please rebase @Th3Mouk

**Comment by Th3Mouk** [comment]
Merged into https://github.com/sonata-project/SonataFormatterBundle/pull/148

**Pull request closed without merging**
