### PR TITLE
Remove useless compiler pass since drop support ckeditor bundle 2 and 3

### PR DESCRIPTION
**Pull request by Th3Mouk**
I waited for several weeks to remove support myself 😢 😄
It missing a little piece of code

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Well, I'll push a v3.0.1... :-(

**Comment by Soullivaneuh** [comment]
Thanks @Th3Mouk

**Comment by Th3Mouk** [comment]
TY

**Comment by Soullivaneuh** [comment]
@Th3Mouk done.

**Pull request merged**
