### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
PHPStan issues also affect the stable branch I think, and should be addressed there IMO

**Comment by greg0ire** [comment]
Actually, one of them is because we no longer require `admin-bundle` on master.

**Comment by core23** [comment]
> Actually, one of them is because we no longer require `admin-bundle` on master since #389
> @core23 please advise 🙏
> 
> If fixed the other one in #435

We should add the admin bundle as a dev dependency. For the next major release, we should use the block bundle FormMapper

**Comment by greg0ire** [comment]
@core23 done, it works :)

**Pull request merged**
