### PR TITLE
Add SF 7 support

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Symfony 7 support
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Blocked by https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/258

**Comment by lemorragia** [comment]
if i'm not mistaken, "symfony/config" is missing the "^7.0" support

**Comment by VincentLanglet** [comment]
> if i'm not mistaken, "symfony/config" is missing the "^7.0" support

Can you provide the PR ? :)

**Comment by lemorragia** [comment]
#788 sure ;-)

**Pull request merged**
