### PR TITLE
ckeditor destroy bug workaround

### PR DESCRIPTION
**Pull request by wojtekdmyszewicz**
@rande - ckeditor destroy bug workaround

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @core23

**Comment by core23** [comment]
@wojtekdmyszewicz Can you say something more? What destroy bug do you mean?

**Comment by greg0ire** [comment]
Please explain in your commit message : 

> what did you do (to fix the bug)
>
> Why did you do that? What was the bug? How does your code fix it?

**Comment by core23** [comment]
Ping @wojtekdmyszewicz

**Pull request closed without merging**
