### PR TITLE
Allow to configure ckeditor toolbar

### PR DESCRIPTION
**Pull request by alexkvak**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Use cases and documentation would be welcomed.

**Comment by alexkvak** [comment]
> Use cases and documentation would be welcomed.
Could you tell me where I can place the docs?

**Comment by Soullivaneuh** [comment]
Maybe here? https://github.com/sonata-project/SonataFormatterBundle/blob/master/Resources/doc/reference/ckeditor_medias.rst

**Comment by alexkvak** [comment]
@Soullivaneuh something like this?

**Comment by alexkvak** [comment]
@rande @Soullivaneuh could you guys merge this PR?

**Comment by OskarStark** [comment]
i don't understand this PR, it is already possible to configure the ck editor options, isn't it?

but maybe the goal or the description of this PR is missleading to me

i use this in Admin:
```php
    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('question')
            ->add('answer', 'sonata_formatter_type', array(
                'event_dispatcher' => $formMapper->getFormBuilder()->getEventDispatcher(),
                'format_field'   => 'answerFormatter',
                'source_field'   => 'rawAnswer',
                'source_field_options'      => array(
                    'attr' => array('class' => 'span10', 'rows' => 20)
                ),
                'listener'       => true,
                'target_field'   => 'answer',
                'ckeditor_toolbar_icons' => $this->getCKEditorOptions()
            ))
        ;
    }

    /**
     * @return array
     */
    protected function getCKEditorOptions()
    {
        return array(
            array(
                'Bold',
                'Italic',
                'Underline',
                '-',
                'Cut',
                'Copy',
                'Paste',
                'PasteText',
                'PasteFromWord',
                '-',
                'Undo',
                'Redo',
                '-',
                'NumberedList',
                'BulletedList',
                '-',
                'Outdent',
                'Indent',
                '-',
                'Blockquote',
                '-',
                //'Image',
                'Link',
                'Unlink',
                //'Table'
            ),
            array('Maximize', 'Source'),
        );
    }
```

thanks for explaining this to me.

Oskar

**Comment by alexkvak** [comment]
@OskarStark 
I need to specify toolbar in default CKEditor which is used in Rich Text Area block (e.g. sonata.block.service.text)

**Comment by OskarStark** [comment]
ah good catch

**Comment by alexkvak** [comment]
@rande is there is any problem with my fix?

**Comment by rande** [comment]
@alexkvak nop, just time ;)

**Comment by alexkvak** [comment]
@rande thanks!

**Pull request merged**
