### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by kunicmarko20**

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Tests are failing, didn't have time to check it. Would be great if someone can check it out.

**Comment by kunicmarko20** [comment]
https://github.com/sonata-project/SonataFormatterBundle/blob/3deb30536aa1431e8ec2354b8baa1e7a9c2565d2/src/DependencyInjection/SonataFormatterExtension.php#L113-L168

I think this one also needs a change.

**Comment by core23** [comment]
Please move `"friendsofsymfony/ckeditor-bundle": "^1.0"` to the `required`section in the composer file

**Comment by kunicmarko20** [comment]
https://github.com/sonata-project/SonataFormatterBundle/blob/master/composer.json#L27 that is already done

**Comment by kunicmarko20** [comment]
I think no upgrade note/changelog is needed, it was already covered by older PRs. @greg0ire Major has my :+1: after this merge.

**Comment by OskarStark** [comment]
@greg0ire please review and merge

**Comment by greg0ire** [comment]
Thanks @kunicmarko20 !

**Pull request merged**
