### PR TITLE
Remove Ckeditor assets

### PR DESCRIPTION
**Pull request by kunicmarko20**
I am targeting this branch, because this is a BC Break.

## Changelog

```markdown
### Removed
- ckeditor assets
```

## Subject

After seeing [this](https://github.com/egeloen/IvoryCKEditorBundle/issues/295) issue I saw that we have the same problem, this should resolve it, and we need to plan a Major soon.

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Need to add upgrade note...

**Comment by OskarStark** [comment]
Shall I merge or do we need to wait for anything?

**Comment by kunicmarko20** [comment]
You can merge.

**Comment by OskarStark** [comment]
Thank you @kunicmarko20 👍

**Pull request merged**
