### PR TITLE
Add support for symfony 6

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

Symfony 6 is supported by https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/239

## Changelog

```markdown
### Added
- Support for Symfony 6
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Now blocked by knplabs/knp-markdown-bundle

**Comment by VincentLanglet** [comment]
Need to follow https://github.com/KnpLabs/KnpMarkdownBundle/pull/111

**Comment by jordisala1991** [comment]
It is really strange to have removed all the code related to ckeditor or markdown, but still have the dependencies, right?

**Comment by jordisala1991** [comment]
Looking at: https://github.com/KnpLabs/KnpMarkdownBundle/releases

Even though we could restore support directly here for markdown, IMO this dependency is not well maintained.
I would vote to remove everything about markdown and have a documentation about how to add it in your own project.

**Comment by VincentLanglet** [comment]
> It is really strange to have removed all the code related to ckeditor or markdown, but still have the dependencies, right?

Indeed, I removed it.

I kept the ckeditor one since we plan on restoring the support.

**Review by core23 — APPROVED** [review]

**Pull request merged**
