### PR TITLE
Compatibility with SF 3 and BC with SF <= 2.8

### PR DESCRIPTION
**Pull request by idchlife**

### CODE REVIEW

**Comment by idchlife** [comment]
@greg0ire @core23 guys, could you possibly tell me, whats wrong here? Thanks @greg0ire for your instructions how to squash commits into one, but still I can't find why Travis build failed. Can't find any useful info in the log https://travis-ci.org/sonata-project/SonataFormatterBundle/builds/110111857

**Comment by greg0ire** [comment]
Just type `make cs`, and then you will see what is wrong with `git diff`

**Comment by idchlife** [comment]
@greg0ire tests clear. Thanks for help!

**Comment by idchlife** [comment]
@core23 @greg0ire can you check this PR

**Comment by greg0ire** [comment]
Good to merge IMO

**Comment by core23** [comment]
Thank you @idchlife

**Pull request merged**
