### PR TITLE
 CKEDITOR Justify plugin

### PR DESCRIPTION
**Pull request by mohammedeisa**
I think that text alignment is very important in any text editor . so i added this line to enable text alignment in CKEDITOR . 
I hope I see this feature in next updates.

### CODE REVIEW

**Comment by OskarStark** [comment]
can you please rebase your PR?

**Comment by OskarStark** [comment]
ping @rande

**Comment by rande** [comment]
This is a BC breack. Cannot we use options from the form type to enable plugins ?

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
