### PR TITLE
Remove deprecated service and compiler

### PR DESCRIPTION
**Pull request by sagikazarmark**
### Changelog

```markdown
### Removed
- Deprecated CKEditor Twig extension service and compiler
```

### Subject

By leaving the now removed service and compiler in the package, but removing the underlying class  3.0.0 is broken and cannot be used. This PR removes the remaining references to that service, should be treated as PATCH.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
> By leaving the now removed service and compiler in the package, but removing the underlying class 3.0.0 is broken and cannot be used.

Could you elaborate? What is the error?

**Comment by sagikazarmark** [comment]
> Fatal error: Class 'Sonata\FormatterBundle\Twig\Extension\CKEditorExtension' not found

I thought it was clear: the class has been removed, the service not.

**Comment by sagikazarmark** [comment]
https://github.com/sonata-project/SonataFormatterBundle/commit/dabe00e1ecef930faf8755f46f9b219b1d7c1ff5

**Comment by Soullivaneuh** [comment]
Oh yes indeed! My mistake. And I forgot some things on composer too.

The tag is recent, unsuable and wrong with composer. 

I think I'll delete v3.0.0 for now and re-push it.

**Comment by sagikazarmark** [comment]
Thanks.

**Comment by Soullivaneuh** [comment]
I removed the tag for now. I'll write test for it, merge your PR, fix the composer issue and push a tag again this evening.

You should remove your sonata vendor folder from your project to not having conflict. :+1:

**Comment by Soullivaneuh** [comment]
@sagikazarmark Can you confirm this solve your issue? All work as expected?

**Comment by sagikazarmark** [comment]
Yes, it works perfectly.

**Comment by Soullivaneuh** [comment]
@sagikazarmark https://github.com/sonata-project/SonataFormatterBundle/releases/tag/3.0.0

Thanks a lot for the report and the help! :+1:

**Pull request merged**
