### PR TITLE
Fix wrong block name

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by rande** [comment]
This is quite annoying bug ... and this is a major BC break.

**Comment by core23** [comment]
Yes, this would be a BC break and could cause problems, but the risk is extreme low. There is also a problem with the ``EmptyBlockService`` which shares the same name.

As far as I know, the only usage for the name is for translation which was fixed by https://github.com/sonata-project/SonataFormatterBundle/pull/124. So I would prefer an upgrade notice and make an exception for this bug.

**Comment by rande** [comment]
It is also used by the PageBundle to reference block type... but broken now ...

**Comment by core23** [comment]
Can you show me the location? Couldn't find anything.

**Comment by rande** [comment]
there is no link, there is a field in the page table call type. And type reference the block code ...

**Comment by core23** [comment]
But the type comes from the service id, not the block name. If it would come from the name, you could not use an ``EmptyBlockService`` or `FormatterBlockService`` because they share the same name.

**Comment by rande** [comment]
Good point1

**Pull request merged**
