### PR TITLE
[DEL] Quick clean up of unused parameter

### PR DESCRIPTION
**Pull request by Th3Mouk**

### CODE REVIEW

**Comment by OskarStark** [comment]
is this a BC Break, or not, because of doing stuff in the extension? @greg0ire

**Comment by greg0ire** [comment]
Yes it is a BC break, because the signature of a public function loses a mandatory argument.

**Comment by greg0ire** [comment]
BTW, why is it even public ? @Th3Mouk : I think you should make it private.

**Comment by Th3Mouk** [comment]
Ok so this PR must wait the creation of 4.x branch

**Comment by greg0ire** [comment]
> Ok so this PR must wait the creation of 4.x branch

Indeed. But it should come soon…

**Comment by OskarStark** [comment]
4.0? at least the next major.

and please add an upgrade notice

**Comment by greg0ire** [comment]
> 4.0? at least the next major.

Not 4.0, 4.x, these are very different things ;) and I think 4.x will be the alias of master. 3.x will be created, not 4.x . When it is out, we will be able to merge this in master.

> and please add an upgrade notice

:+1: In that case, it is just an internal method that changes, but that will teach us to make method that should be private public ;) 
The upgrade notice title should read : "From 3.x to 4.x" or something like that.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
